import React from 'react';
import { StyleSheet, View } from 'react-native';
import { Button, Text } from 'react-native-paper';

export default function QRLoginScreen({ navigation }) {
  return (
    <View style={styles.container}>
      <Text variant="titleMedium">QR Code Login</Text>
      <Text style={styles.paragraph}>
        Placeholder: Camera scanner to read session QR generated by clinic/portal. After scanning, exchange token with ABDM gateway (sandbox) and log user in.
      </Text>
      <Button mode="contained" style={styles.btn} onPress={() => navigation.goBack()}>Simulate Scan</Button>
    </View>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, padding: 16, paddingTop: 28 },
  paragraph: { marginTop: 12, lineHeight: 18 },
  btn: { marginTop: 24 }
});
